#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "vm" {
  source = "./module-gce"

  allow_stopping_for_update = true
  boot_disk_auto_delete     = true
  boot_disk_device_name     = ""
  boot_disk_image           = "debian-cloud/debian-10"
  boot_disk_size            = 5
  boot_disk_type            = "pd-standard"
  customer                  = var.customer
  egress_allow_ports = [

  ]

  egress_allow_protocol = "all"
  egress_destination_ranges = [

  ]
  egress_disabled      = false
  egress_firewall_name = "juliencycloidegress"
  env                  = var.env
  file_content         = ""
  ingress_allow_ports = [
    "22"
  ]

  ingress_allow_protocol = "tcp"
  ingress_disabled       = false
  ingress_firewall_name  = "juliencycloidingress"
  ingress_source_ranges = [

  ]

  ingress_source_tags = [

  ]

  instance_extra_labels = {
  }

  instance_name = "Learning-Cycloid"
  instance_tags = [
    "julien-learning-cycloid"
  ]

  machine_type = "e2-small"
  network      = "accenture-lab-cycloid-workers-accenture-lab-prod-network"
  network_ip   = ""
  project      = var.project
}

